### ISSUE TITLE
Previous seasons' data

### ISSUE THREAD

**Issue by SamsadSajid** [vaastav/Fantasy-Premier-League#5] opened 2018-11-19 20:33 UTC
I see you have only 3 seasons. **2016-17, 2017-18, 2018-19**. 
I think it would be great if there were more data from the past season. What I meant is, it would be nice to have at least previous 5/6 seasons' data.

Do you think you can add more data from the past seasons? Or if you can't, can you tell me the workflow of your current project so that I can gather those previous seasons' data. 

After that, I can create a branch and make a PR. You can merge it with the **master branch** if everything passes.

**Comment by vaastav** [comment] 2018-11-20 06:08
I would personally love to have data from the past seasons.
The issue is that the official fpl site takes down the data of the previous season at the start of every new season. So, my scripts can only scrape the data which the official fpl site/api is providing which sadly doesn't include full data of seasons past.
If you do find those datasets then please go ahead and make a PR to add them to the repo and I will gladly merge them with the master branch :)

**Comment by vaastav** [comment] 2018-11-23 07:49
Closing this issue!

**Closed by vaastav** 2018-11-23 07:49 UTC
