### ISSUE TITLE
teams_scraper only pulling history & chips 

### ISSUE THREAD

**Issue by mikeandrewjeski** [vaastav/Fantasy-Premier-League#10] opened 2019-05-31 14:20 UTC
Hi, not sure if it's my python version, pandas version or what, but when running teams_scraper I get only history & chips, along with a rather ugly error: TypeError: object of type 'NoneType' has no len(). Any help is greatly appreciated.  Using python 3.6.7 & pandas (0.23.4) from pip.
Also occurs with python 3.7.3 & pandas 0.24.2

Traceback (most recent call last):
  File "teams_scraper.py", line 24, in <module>
    main()
  File "teams_scraper.py", line 19, in main
    parse_entry_history(summary, output_folder)
  File "/mnt/c/mike/notes/fpl/vaastav/Fantasy-Premier-League/parsers.py", line 61, in parse_entry_history
    profile_df = pd.DataFrame.from_records(profile_data)
  File "/home/mandrew/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 1269, in from_records
    coerce_float=coerce_float)
  File "/home/mandrew/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 7467, in _to_arrays
    if not len(data):
TypeError: object of type 'NoneType' has no len()

**Comment by vaastav** [comment] 2019-05-31 20:16
Hmm I am not sure what is going on here. Can you tell me what your team ID is so that I can try reproducing the error on my computer? Sorry for the issue.

**Comment by mikeandrewjeski** [comment] 2019-05-31 20:35
cheers mate,  no need to apologise.  use 2864

**Comment by vaastav** [comment] 2019-06-02 22:38
This is a weird bug related to how pandas deals with dictionaries. It will take another day or 2 for me to fix. Apologies for the delay.

**Comment by vaastav** [comment] 2019-06-02 22:42
The only thing not working is the profile parsing. I have removed that for now and you should be able to download your stats correctly.

**Comment by jeski** [comment] 2019-06-02 23:13
cheers mate.  don't go to any trouble on my part

**Comment by vaastav** [comment] 2019-06-02 23:17
Its probably because of the kit not being set in the profile. I need to find a better way of handling that I reckon. Thanks for bringing this to my attention :)

**Comment by mikeandrewjeski** [comment] 2019-06-03 16:03
cheers mate, works a charm!

**Comment by vaastav** [comment] 2019-06-12 12:05
Closing this issue for now! Glad, it worked out for you.

**Closed by vaastav** 2019-06-12 12:05 UTC
